"""长期记忆内核（与 AstrBot API 完全解耦，可以脱离 AstrBot 单独测试）。"""

from .config import Settings, cfg_get
from .extract import (
    EXTRACT_SYSTEM,
    ExtractedItem,
    MemoryExtractor,
    Turn,
    extract_json_object,
    format_existing_for_prompt,
    parse_extraction,
)
from .model import (
    KIND_EVENT,
    KIND_FACT,
    KIND_LABELS,
    KIND_OTHER,
    KIND_PREFERENCE,
    KIND_PROMISE,
    KIND_RELATION,
    KINDS,
    PINNABLE_KINDS,
    SCOPE_GLOBAL,
    SCOPE_LABELS,
    SCOPE_SESSION,
    SCOPE_USER,
    SCOPES,
    KINDS,
    KIND_LABELS,
    Memory,
    ScoreWeights,
    cosine_overlap,
    cosine_vector,
    humanize_ago,
    is_group_session,
    jaccard,
    keyword_hit_score,
    now_ts,
    normalize,
    recency_score,
    score_memory,
    tokenize,
    truncate,
)
from .privacy import (
    SENSITIVE_KEYWORDS,
    SENSITIVE_PATTERNS,
    allows,
    decide_scope,
    describe_blocked,
    detect_sensitive,
    is_sensitive,
)
from .prompt import (
    GROUP_NOTE,
    MARKER,
    RULES_BLOCK,
    RULES_MARKER,
    render_blocked_hint,
    render_digest,
    render_memory_block,
)
from .retriever import RetrievalResult, Retriever
from .store import MemoryStore, row_to_memory

__all__ = [
    "EXTRACT_SYSTEM",
    "GROUP_NOTE",
    "RULES_BLOCK",
    "RULES_MARKER",
    "KINDS",
    "KIND_EVENT",
    "KIND_FACT",
    "KIND_LABELS",
    "KIND_OTHER",
    "KIND_PREFERENCE",
    "KIND_PROMISE",
    "KIND_RELATION",
    "MARKER",
    "PINNABLE_KINDS",
    "SCOPES",
    "SCOPE_GLOBAL",
    "SCOPE_LABELS",
    "SCOPE_SESSION",
    "SCOPE_USER",
    "SENSITIVE_KEYWORDS",
    "SENSITIVE_PATTERNS",
    "ExtractedItem",
    "Memory",
    "MemoryExtractor",
    "MemoryStore",
    "RetrievalResult",
    "Retriever",
    "ScoreWeights",
    "Settings",
    "Turn",
    "allows",
    "cfg_get",
    "cosine_overlap",
    "cosine_vector",
    "decide_scope",
    "describe_blocked",
    "detect_sensitive",
    "extract_json_object",
    "format_existing_for_prompt",
    "humanize_ago",
    "is_group_session",
    "is_sensitive",
    "jaccard",
    "keyword_hit_score",
    "normalize",
    "now_ts",
    "parse_extraction",
    "recency_score",
    "render_blocked_hint",
    "render_digest",
    "render_memory_block",
    "row_to_memory",
    "score_memory",
    "tokenize",
    "truncate",
]

